/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.ResultSetTableModel;
import koneksi.koneksi;

/**
 *
 * @author Asus
 */
public class kasir extends javax.swing.JFrame {

    /**
     * Creates new form kasir
     */
    DefaultTableModel model;
    public kasir() {
        initComponents();
        String [] judul ={"n.pinjaman","n.anggota","nama","tgl angsuran","total pin","sisa pin",
            "kode angs","jatuh tempo","angs ke","pokok","bunga","denda","total angs"};
        model = new DefaultTableModel(judul,0);
        table.setModel(model);
        tampilkan();
        TampilTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        anggota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        denda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bunga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        kode_angs = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jatuh_tempo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        angs_ke = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pinjaman = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        angs_pok = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        total_angs = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sisa_pin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        total_pin = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, -1));

        jLabel2.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("no anggota");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        anggota.setBackground(new java.awt.Color(255, 255, 255));
        anggota.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        anggota.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 140, -1));

        jLabel4.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("tgl angsuran");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        tanggal.setBackground(new java.awt.Color(255, 255, 255));
        tanggal.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        tanggal.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 140, -1));

        jLabel5.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("denda");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        denda.setBackground(new java.awt.Color(255, 255, 255));
        denda.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        denda.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 130, -1));

        jLabel6.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("angsuran bunga ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        bunga.setBackground(new java.awt.Color(255, 255, 255));
        bunga.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        bunga.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(bunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 130, -1));

        jLabel7.setFont(new java.awt.Font("Calisto MT", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("formulir angsuran");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        kode_angs.setBackground(new java.awt.Color(255, 255, 255));
        kode_angs.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        kode_angs.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(kode_angs, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 130, -1));

        jLabel8.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("jatuh tempo");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jatuh_tempo.setBackground(new java.awt.Color(255, 255, 255));
        jatuh_tempo.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jatuh_tempo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jatuh_tempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 130, -1));

        jLabel9.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("angsuran ke");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        angs_ke.setBackground(new java.awt.Color(255, 255, 255));
        angs_ke.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        angs_ke.setForeground(new java.awt.Color(0, 0, 0));
        angs_ke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angs_keActionPerformed(evt);
            }
        });
        jPanel1.add(angs_ke, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 130, -1));

        jLabel10.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("no pinjaman");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        pinjaman.setBackground(new java.awt.Color(255, 255, 255));
        pinjaman.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        pinjaman.setForeground(new java.awt.Color(0, 0, 0));
        pinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamanActionPerformed(evt);
            }
        });
        jPanel1.add(pinjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 140, -1));

        jLabel11.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("angsuran pokok");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        angs_pok.setBackground(new java.awt.Color(255, 255, 255));
        angs_pok.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        angs_pok.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(angs_pok, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 130, -1));

        jLabel12.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("total angsuran");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        total_angs.setBackground(new java.awt.Color(255, 255, 255));
        total_angs.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        total_angs.setForeground(new java.awt.Color(0, 0, 0));
        total_angs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_angsActionPerformed(evt);
            }
        });
        jPanel1.add(total_angs, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 130, -1));

        jLabel13.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("sisa pinjaman");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        sisa_pin.setBackground(new java.awt.Color(255, 255, 255));
        sisa_pin.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        sisa_pin.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(sisa_pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 140, -1));

        jLabel14.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("total pinjaman");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        total_pin.setBackground(new java.awt.Color(255, 255, 255));
        total_pin.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        total_pin.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(total_pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 140, -1));

        jLabel15.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("kode angsuran");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan/icons8-bank-building-64.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel16.setFont(new java.awt.Font("Century751 No2 BT", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("KSU");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 100, 50));

        jLabel17.setFont(new java.awt.Font("Century751 No2 BT", 3, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("AMO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 50));

        jButton1.setText("simpan");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jButton2.setText("hapus");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jButton3.setText("edit");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 70, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 620, 90));

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan/icons8-attach-resume-female-50.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel19.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("logout");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, 50, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 70, 65));

        background.setFont(new java.awt.Font("Calisto MT", 0, 14)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan/cat.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinjamanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        koneksi Objkoneksi = new koneksi();
        Connection con = Objkoneksi.bukakoneksi();
        Statement st = con.createStatement();
        String sql = "INSERT INTO kasir(no_pinjaman, no_anggota, nama, tgl_angsuran, total_pinjaman, sisa_pinjaman, kode_angsuran, jatuh_tempo, angsuran_ke, "
                + "angsuran_pokok, angsuran_bunga, denda, total_angsuran) VALUES "
                +"('"+pinjaman.getText()+"','"+anggota.getText()+"','"+nama.getText() +"','"+tanggal.getText()+"','"+total_pin.getText()+"','"+sisa_pin.getText()+"'," +
                    "'"+kode_angs.getText()+"','"+jatuh_tempo.getText()+"','"+angs_ke.getText()+"','"+angs_pok.getText()+"','"+bunga.getText()+"',"
                + "'"+denda.getText()+"','"+total_angs.getText()+"')";
            int row = st.executeUpdate(sql);
            
            if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah ditambahkan ke" +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
                 
               con.close();
                }
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Data tidak ditambahkan ke" +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
    }
  TampilTabel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void angs_keActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angs_keActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angs_keActionPerformed

    private void total_angsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_angsActionPerformed
        // TODO add your handling code here:
        int nilai1 = Integer.parseInt(angs_pok.getText());
        int nilai2 = Integer.parseInt(bunga.getText());
        int nilai3 = Integer.parseInt(denda.getText());

        int tambah = nilai1+nilai2+nilai3;
        
        total_angs.setText(String.valueOf(tambah));
        System.out.println(total_angs);
    }//GEN-LAST:event_total_angsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            
        koneksi Objkoneksi = new koneksi();
        Connection con = Objkoneksi.bukakoneksi();
        Statement st = con.createStatement();

        String sql = "update kasir set no_pinjaman = '"+pinjaman.getText()+"',no_anggota = '"+anggota.getText()+"',nama = '"+nama.getText() +"',"
                + "tgl_angsuran = '"+tanggal.getText()+"',total_pinjaman = '"+total_pin.getText()+"',sisa_pinjaman = '"+sisa_pin.getText()+"',"
                + "kode_angsuran = '"+kode_angs.getText()+"',jatuh_tempo = '"+jatuh_tempo.getText()+"',angsuran_ke = '"+angs_ke.getText()+"',"
                + "angsuran_pokok = '"+angs_pok.getText()+"',angsuran_bunga = '"+bunga.getText()+"',"
                + "denda = '"+denda.getText()+"',total_angsuran = '"+total_angs.getText()+"'" ;

         int row = st.executeUpdate(sql);
         if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah di update "
                        ,"infomasi",JOptionPane.INFORMATION_MESSAGE);
                 con.close();
                }
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Data tidak diUbah","infomasi",JOptionPane.
                INFORMATION_MESSAGE);
    }
 TampilTabel();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
        koneksi Objkoneksi = new koneksi();
        Connection con = Objkoneksi.bukakoneksi();
        Statement st = con.createStatement();
        String sql = "delete from kasir where no_pinjaman = '"+pinjaman.getText()+"' ";
        int row = st.executeUpdate(sql);
        if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah dihapus dari " +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
               
                con.close();

                }
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Data tidak dihapus","infomasi",JOptionPane.
                INFORMATION_MESSAGE);
    }
    TampilTabel();  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel2AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel2AncestorMoved

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        login k = new login();
        k.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anggota;
    private javax.swing.JTextField angs_ke;
    private javax.swing.JTextField angs_pok;
    private javax.swing.JLabel background;
    private javax.swing.JTextField bunga;
    private javax.swing.JTextField denda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jatuh_tempo;
    private javax.swing.JTextField kode_angs;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField pinjaman;
    private javax.swing.JTextField sisa_pin;
    private javax.swing.JTable table;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField total_angs;
    private javax.swing.JTextField total_pin;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
       int row = table.getRowCount();
        for(int a= 0; a<row;a++){
            model.removeRow(0);
        }
    
        
    }

    private void TampilTabel() {
        try {
            koneksi Objkoneksi = new koneksi();
            Connection con = Objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String sql = "SELECT * FROM kasir";
            ResultSet set = st.executeQuery(sql);
            //menampilkan data ke Tabel
            ResultSetTableModel model = new ResultSetTableModel(set);
            table.setModel(model);

            
        }
        catch(SQLException e) { 
            System.out.println("gagal query");
        }
    }
}
