/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.ResultSetTableModel;
import koneksi.koneksi;

/**
 *
 * @author Asus
 */
public class pembukuan extends javax.swing.JFrame {

    /**
     * Creates new form pembukuan
     */
    DefaultTableModel model;
    public pembukuan() {
        initComponents();
        String [] judul ={"bulan","simpanan","pinjaman","angsuran","pemasukan","pengeluaran","tanggal"};
        model =new DefaultTableModel(judul,0);
        table.setModel(model);
        tampilkan();
        TampilTabel();
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jumlah_simpanan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jumlah_pinjaman = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tanggal_data = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bulan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        total_pemasukkan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jumlah_angsuran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        total_pengeluaran = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tabel = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("jumlah simpanan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jumlah_simpanan.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jumlah_simpanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_simpananActionPerformed(evt);
            }
        });
        jPanel1.add(jumlah_simpanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 120, -1));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("jumlah pinjaman");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jumlah_pinjaman.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jPanel1.add(jumlah_pinjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 120, -1));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("tanggal data");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        tanggal_data.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jPanel1.add(tanggal_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 120, -1));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("bulan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        bulan.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jPanel1.add(bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 120, -1));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("total pemasukkan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        total_pemasukkan.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        total_pemasukkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_pemasukkanActionPerformed(evt);
            }
        });
        jPanel1.add(total_pemasukkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 120, -1));

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("jumlah angsuran");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jumlah_angsuran.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jPanel1.add(jumlah_angsuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 120, -1));

        jLabel8.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("total pengeluaran");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        total_pengeluaran.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jPanel1.add(total_pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 120, -1));

        jLabel9.setFont(new java.awt.Font("Century751 No2 BT", 3, 32)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("AMO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 100, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan/icons8-bank-building-64.png"))); // NOI18N
        jLabel10.setText("jLabel2");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        jLabel11.setFont(new java.awt.Font("Century751 No2 BT", 3, 32)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("KSU");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 100, 50));

        jLabel13.setFont(new java.awt.Font("Century751 No2 BT", 3, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("laporan keuangan");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 220, 50));

        jButton1.setText("hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jButton2.setText("edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jButton3.setText("simpan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tabel.setViewportView(table);

        jPanel1.add(tabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 540, 90));

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan/icons8-brown-hair-business-lady-in-red-shirt-50.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel14.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("logout");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, 50, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 70, 65));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan/gold-fabric-cloth-background-texture_49683-3812.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 559, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
        koneksi Objkoneksi = new koneksi();
        Connection con = Objkoneksi.bukakoneksi();
        Statement st = con.createStatement();
        String sql = "INSERT INTO pembukuan(bulan , jumlah_simpanan, jumlah_pinjaman, jumlah_angsuran, total_pemasukkan, total_pengeluaran, tanggal_data) VALUES "
                +"('"+bulan.getText()+"','"+jumlah_simpanan.getText() +"','"+jumlah_pinjaman.getText()+"','"+jumlah_angsuran.getText()+"'," +
                    "'"+total_pemasukkan.getText()+"','"+total_pengeluaran.getText()+"','"+tanggal_data.getText()+"')";
            int row = st.executeUpdate(sql);
            
            if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah ditambahkan ke" +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
                 
               con.close();
                }
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Data tidak ditambahkan ke" +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
    }
        TampilTabel();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        koneksi Objkoneksi = new koneksi();
        Connection con = Objkoneksi.bukakoneksi();
        Statement st = con.createStatement();

        String sql = "update pembukuan set jumlah_simpanan ='"+jumlah_simpanan.getText()+"',jumlah_pinjaman = '"+jumlah_pinjaman.getText()+"',"
                + "jumlah_angsuran = '"+jumlah_angsuran.getText()+"',total_pemasukkan = '"+total_pemasukkan.getText()+"',"
                + "total_pengeluaran ='"+total_pengeluaran.getText()+"',tanggal_data ='"+tanggal_data.getText()+"' "
                + "where bulan = '"+bulan.getText()+"'" ;

         int row = st.executeUpdate(sql);
         if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah di update "
                        ,"infomasi",JOptionPane.INFORMATION_MESSAGE);
                 con.close();
                }
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Data tidak diUbah","infomasi",JOptionPane.
                INFORMATION_MESSAGE);
    }
 TampilTabel();

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        koneksi Objkoneksi = new koneksi();
        Connection con = Objkoneksi.bukakoneksi();
        Statement st = con.createStatement();
        String sql = "delete from pembukuan where bulan = '"+bulan.getText()+"' ";
        int row = st.executeUpdate(sql);
        if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah dihapus dari " +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
               
                con.close();

                }
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Data tidak dihapus","infomasi",JOptionPane.
                INFORMATION_MESSAGE);
    }
    TampilTabel();  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel2AncestorMoved

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        login k = new login();
        k.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jumlah_simpananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_simpananActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jumlah_simpananActionPerformed

    private void total_pemasukkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_pemasukkanActionPerformed
        // TODO add your handling code here:
        int nilai1 = Integer.parseInt(jumlah_simpanan.getText());
        int nilai2 = Integer.parseInt(jumlah_angsuran.getText());
        
        int tambah = nilai1+nilai2;
        
        total_pemasukkan.setText(String.valueOf(tambah));
        System.out.println(total_pemasukkan);
    }//GEN-LAST:event_total_pemasukkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembukuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembukuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembukuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembukuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembukuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField bulan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jumlah_angsuran;
    private javax.swing.JTextField jumlah_pinjaman;
    private javax.swing.JTextField jumlah_simpanan;
    private javax.swing.JScrollPane tabel;
    private javax.swing.JTable table;
    private javax.swing.JTextField tanggal_data;
    private javax.swing.JTextField total_pemasukkan;
    private javax.swing.JTextField total_pengeluaran;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
        int row = table.getRowCount();
        for(int a= 0; a<row;a++){
            model.removeRow(0);
        }
    }
        

    
        
    
    private void TampilTabel() {
        
            //menampilkan data ke Tabel
            try {
            koneksi Objkoneksi = new koneksi();
            Connection con = Objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String sql = "SELECT * FROM pembukuan";
            ResultSet set = st.executeQuery(sql);
            //menampilkan data ke Tabel
            ResultSetTableModel model = new ResultSetTableModel(set);
            table.setModel(model);

            
        }
        catch(SQLException e) { 
            System.out.println("gagal query");
        }

            
        }
       
    }
    

