/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.ResultSetTableModel;
import koneksi.koneksi;

/**
 *
 * @author Asus
 */
public class pinjaman extends javax.swing.JFrame {

    /**
     * Creates new form pinjaman
     */
    public pinjaman() {
        initComponents();
        TampilTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        anggota = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        pinjaman = new javax.swing.JTextField();
        tujuan = new javax.swing.JTextField();
        bunga = new javax.swing.JTextField();
        jaminan = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        waktu = new javax.swing.JTextField();
        angsuran = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        realisasi = new javax.swing.JTextField();
        kredit = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        bacground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("formulir Pendaftaran Pinjaman");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 290, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan/icons8-bank-building-64.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 60));

        jLabel9.setFont(new java.awt.Font("Century751 No2 BT", 3, 29)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("KSU");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, 40));

        jLabel10.setFont(new java.awt.Font("Century751 No2 BT", 3, 29)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("AMO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 110, 40));

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan/pembukuan.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("logout");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 40, 50, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 70, 65));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("No anggota");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 135, -1, -1));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 165, -1, -1));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Jumlah pinjaman");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, -1, -1));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tujuan pinjaman");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 255, -1, -1));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("No jaminan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 135, -1, -1));

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Jangka waktu");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 165, -1, -1));

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Jumlah angsuran");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 195, -1, -1));

        jLabel14.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Tanggal kredit ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 225, -1, -1));

        jLabel15.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Bunga");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 285, -1, -1));

        jLabel16.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Jaminan");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 105, -1, -1));

        jLabel17.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Tanggal realisasi ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 255, -1, -1));

        jLabel18.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("No kredit");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, -1, -1));

        jLabel19.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Alamat");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 195, -1, -1));

        anggota.setBackground(new java.awt.Color(255, 255, 255));
        anggota.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        anggota.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 135, 150, -1));

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 165, 150, -1));

        alamat.setBackground(new java.awt.Color(255, 255, 255));
        alamat.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        alamat.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 195, 150, -1));

        pinjaman.setBackground(new java.awt.Color(255, 255, 255));
        pinjaman.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        pinjaman.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(pinjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 225, 150, -1));

        tujuan.setBackground(new java.awt.Color(255, 255, 255));
        tujuan.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        tujuan.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(tujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 255, 150, -1));

        bunga.setBackground(new java.awt.Color(255, 255, 255));
        bunga.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        bunga.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(bunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 285, 150, -1));

        jaminan.setBackground(new java.awt.Color(255, 255, 255));
        jaminan.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jaminan.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jaminan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 105, 150, -1));

        no.setBackground(new java.awt.Color(255, 255, 255));
        no.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        no.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 135, 150, -1));

        waktu.setBackground(new java.awt.Color(255, 255, 255));
        waktu.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        waktu.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 165, 150, -1));

        angsuran.setBackground(new java.awt.Color(255, 255, 255));
        angsuran.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        angsuran.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(angsuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 195, 150, -1));

        tanggal.setBackground(new java.awt.Color(255, 255, 255));
        tanggal.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        tanggal.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 225, 150, -1));

        realisasi.setBackground(new java.awt.Color(255, 255, 255));
        realisasi.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        realisasi.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(realisasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 255, 150, -1));

        kredit.setBackground(new java.awt.Color(255, 255, 255));
        kredit.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        kredit.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(kredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 105, 150, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 153, 0));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 70, -1));

        jButton3.setBackground(new java.awt.Color(153, 153, 0));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 70, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "n.kredit", "n.angg", "nama", "alamat", "jum.pin", "tujuan", "bunga", "jaminan", "n.jaminan", "waktu", "angsuran", "tgl kredit", "tgl realisasi"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 620, 90));

        bacground.setFont(new java.awt.Font("Book Antiqua", 0, 15)); // NOI18N
        bacground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simpan/layar.jpg"))); // NOI18N
        jPanel1.add(bacground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2AncestorMoved

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        login k = new login();
        k.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        koneksi Objkoneksi = new koneksi();
        Connection con = Objkoneksi.bukakoneksi();
        Statement st = con.createStatement();
        String sql = "INSERT INTO pinjaman(no_kredit, no_anggota, nama, alamat, jumlah_pinjaman, tujuan_pinjaman, bunga, jaminan, no_jaminan, "
                + "jangka_waktu, jumlah_angsuran, tanggal_kredit, tanggal_realisasi) VALUES "
                +"('"+kredit.getText()+"','"+anggota.getText()+"','"+nama.getText() +"','"+alamat.getText()+"','"+pinjaman.getText()+"','"+tujuan.getText()+"'," +
                    "'"+bunga.getText()+"','"+jaminan.getText()+"','"+no.getText()+"','"+waktu.getText()+"','"+angsuran.getText()+"',"
                + "'"+tanggal.getText()+"','"+realisasi.getText()+"')";
            int row = st.executeUpdate(sql);
            
            if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah ditambahkan ke" +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
                 
               con.close();
                }
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Data tidak ditambahkan ke" +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
    }
  TampilTabel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        koneksi Objkoneksi = new koneksi();
        Connection con = Objkoneksi.bukakoneksi();
        Statement st = con.createStatement();
        String sql = "delete from pinjaman where no_kredit = '"+kredit.getText()+"' ";
        int row = st.executeUpdate(sql);
        if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah dihapus dari " +
                        " database","infomasi",JOptionPane.INFORMATION_MESSAGE);
               
                con.close();

                }
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Data tidak dihapus","infomasi",JOptionPane.
                INFORMATION_MESSAGE);
    }
    TampilTabel();  

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
        koneksi Objkoneksi = new koneksi();
        Connection con = Objkoneksi.bukakoneksi();
        Statement st = con.createStatement();

        String sql = "update pinjaman set no_anggota = '"+anggota.getText()+"',nama = '"+nama.getText() +"',alamat = '"+alamat.getText()+"',jumlah_pinjaman = '"+pinjaman.getText()+"',tujuan_pinjaman = '"+tujuan.getText()+"'," +
                    "bunga = '"+bunga.getText()+"',jaminan = '"+jaminan.getText()+"',no_jaminan = '"+no.getText()+"',jangka_waktu = '"+waktu.getText()+"',jumlah_angsuran = '"+angsuran.getText()+"',"
                + "tanggal_kredit = '"+tanggal.getText()+"',tanggal_realisasi = '"+realisasi.getText()+"' where no_kredit = '"+kredit.getText()+"'" ;

         int row = st.executeUpdate(sql);
         if (row ==1){
                JOptionPane.showMessageDialog(null,"Data sudah di update "
                        ,"infomasi",JOptionPane.INFORMATION_MESSAGE);
                 con.close();
                }
    }
    catch(SQLException e){
        JOptionPane.showMessageDialog(null,"Data tidak diUbah","infomasi",JOptionPane.
                INFORMATION_MESSAGE);
    }
 TampilTabel();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pinjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField anggota;
    private javax.swing.JTextField angsuran;
    private javax.swing.JLabel bacground;
    private javax.swing.JTextField bunga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jaminan;
    private javax.swing.JTextField kredit;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no;
    private javax.swing.JTextField pinjaman;
    private javax.swing.JTextField realisasi;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField tujuan;
    private javax.swing.JTextField waktu;
    // End of variables declaration//GEN-END:variables

    private void TampilTabel() {
        try {
            koneksi Objkoneksi = new koneksi();
            Connection con = Objkoneksi.bukakoneksi();
            Statement st = con.createStatement();
            String sql = "SELECT * FROM pinjaman";
            ResultSet set = st.executeQuery(sql);
            //menampilkan data ke Tabel
            ResultSetTableModel model = new ResultSetTableModel(set);
            tabel.setModel(model);

            
        }
        catch(SQLException e) { 
            System.out.println("gagal query");
        }
    
    }
}
